#!/usr/bin/env node
const os = require('os')

const { readFile } = require('fs')
const { promisify } = require('util')

const readFileAsync = promisify(readFile)

function collector(entryParts) {
    return [entryParts[2], entryParts[3]]
}

function constructor(entryParts) {
    return entryParts.join(' ')
}

function getSelf(ifname) {
    const hostname = os.hostname()
    const { address } = os.networkInterfaces()[ifname][0]
    const pair = `${address} ${hostname}`
    return pair
}

async function main() {
    try {
        const string = await readFileAsync(process.argv[2], 'utf8')
        const entryArray = string.split('\n')
        const splitEntryArray = entryArray.map(entry => entry.split(' '))
        const filteredEntryArray = splitEntryArray.map(collector)
        const formedEntry = filteredEntryArray.map(constructor)
        const formedString = formedEntry.join('\n')
        console.log(`${getSelf('lan')}\n${formedString}`)
        process.exit(0)
    } catch (e) {
        console.error(e.message)
        // console.error('biubiubiu!')
        process.exit(e.errno || -1)
    }
}

main()
